<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'IdiormMethodMissingException' => $vendorDir . '/j4mie/idiorm/idiorm.php',
    'IdiormResultSet' => $vendorDir . '/j4mie/idiorm/idiorm.php',
    'IdiormString' => $vendorDir . '/j4mie/idiorm/idiorm.php',
    'IdiormStringException' => $vendorDir . '/j4mie/idiorm/idiorm.php',
    'Model' => $vendorDir . '/j4mie/paris/paris.php',
    'ORM' => $vendorDir . '/j4mie/idiorm/idiorm.php',
    'ORMWrapper' => $vendorDir . '/j4mie/paris/paris.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'ParisMethodMissingException' => $vendorDir . '/j4mie/paris/paris.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
